name:                Str2Split
version:             0.1.0.0
github:              "mouse07410/Str2Split"
license:             BSD3
author:              "Mouse"
maintainer:          "uri@mit.edu"
copyright:           "Copyright (C) 2019 Mouse"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mouse07410/Str2Split#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Str2Split-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Str2Split

tests:
  Str2Split-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Str2Split
    - hspec >= 2.7.1
    - QuickCheck >= 2.13
